Error: Timezone is always set to 'America/Chicago'!
The Config class has a property, not a method. The method reference causes the time zone to never be taken from the openDCIM configuration, but hardcoded to 'America/Chicago' :-(.